### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by qyh214** [ShinDarth/TC-JSON-API#1]
1.IN .env what parameters can be set?
2.TC DB is multi-language and multi-language information  how to return?now for example only return item_template not local_item,maybe we can return all or can be choose
3.Access control.For example,connect with other account control center or have own account system that like dev.battle.net ,If it is public, there will be security problems or pose a threat to the server.

**Comment by FrancescoBorzi** [comment]
1. currently just the DB_\* ones

2 and 3 can be discussed, but please open one separated Issue for each suggestion.

Thank you!
