### ISSUE TITLE
Error php

### ISSUE THREAD

**Issue by Zaekor** [ShinDarth/TC-JSON-API#15]
Hello,

Here I have a php error I do not understand why I all properly installed

[Here is a picture](http://img15.hostingpics.net/pics/247076281.png)

Additional Info

Use php-5.6.18
Use Uwamp
Use DB TrinityCore 6.x

**Comment by FrancescoBorzi** [comment]
Did you set the file permissions properly as explained in the instructions?

**Comment by Zaekor** [comment]
The file .env Is configured

**Comment by FrancescoBorzi** [comment]
I don't mean the .env file, I mean all files permissions:

> Ensure that the entire folder TC-JSON-API (including all its files and subfolders) have the proper file permissions

which file permissions did you set?

**Comment by Zaekor** [comment]
It's good I forgot to go .env.example to .env 

I'm a noob :P

**Comment by FrancescoBorzi** [comment]
did you resolve?

**Comment by Zaekor** [comment]
Yes its good ! 

And thank you for this API

**Comment by FrancescoBorzi** [comment]
you're welcome :D feel free to contribute
