### ISSUE TITLE
How to show debug info?

### ISSUE THREAD

**Issue by darrkz** [ShinDarth/TC-JSON-API#16]
I try TC-JSON-API recently.
But these days when I try to query,it display that : http 500
when I open  /TC-JSON-API/public/index.php
It told me that "Whoops, looks like something went wrong."
I open php error display and found nothing about this error.
How to set  TC-JSON-API to show debug info?

**Comment by Helias** [comment]
It shows in storage/logs/laravel.log but probably you should set the permissions of the directories storage and logs to allow the creation of the logs, so put 775 the permissions of storage and logs.

You can use chmod 775, refresh the page where you get the error and check if laravel.log has been created in storage/logs

**Comment by avengerweb** [comment]
https://github.com/ShinDarth/TC-JSON-API/pull/17
