### ISSUE TITLE
ERROR: API not found

### ISSUE THREAD

**Issue by alexandre433** [ShinDarth/TC-JSON-API#19]
Hello,

I've tried to change the path a bunch of times and it still gives me the error 
"ERROR: API not found, please edit your config.js file and set the path of your TrinityCore JSON API istance."

I've also tried to change the db's conection manually like indicated on the tutorial but still nothing..

**Comment by FrancescoBorzi** [comment]
did you set the file permissions?

**Comment by alexandre433** [comment]
Yes

**Comment by FrancescoBorzi** [comment]
ok check /storage/logs and see which errors you got

**Comment by alexandre433** [comment]
Nothing

**Comment by avengerweb** [comment]
Show your configs here.

**Comment by alexandre433** [comment]
they are the default ones but with a change on the db's names instead of "auth" its "auth1" and so on.

**Comment by FrancescoBorzi** [comment]
@alexandre433 are you sure to have set the right permissions? if it does not work and you are not getting errors, the it isn't doing anything at all

**Comment by alexandre433** [comment]
I've set the permissions, but tell me how do YOU do it. 
I've tried so many times and everything, reinstalling it, renaming, etc.

**Comment by FrancescoBorzi** [comment]
did you install all the requirements?

**Comment by alexandre433** [comment]
yes

**Comment by FrancescoBorzi** [comment]
how did you set the permissions? did you include all files and subfolders?

**Comment by alexandre433** [comment]
Yes I did, all of them

**Comment by FrancescoBorzi** [comment]
@alexandre433 can you successfully install a clean laravel project?

**Comment by alexandre433** [comment]
How do I do that?

**Comment by FrancescoBorzi** [comment]
https://laravel.com/

just because I don't know anything else you could try, it's very strange

**Comment by alexandre433** [comment]
oh that I've already installed, composer aswell

**Comment by FrancescoBorzi** [comment]
just try to setup a single project

**Comment by alexandre433** [comment]
but it said It requiered both

**Comment by alexandre433** [comment]
Could you add me on skype, so you could solve the error faster?
Skype - alexandria433

**Comment by alexandre433** [comment]
bump

**Comment by alexandre433** [comment]
UPDATE SOLVED

PHP Version Was OLD
