### ISSUE TITLE
Whoops! Something went wrong! (WelcomeController)

### ISSUE THREAD

**Issue by malex1024** [ShinDarth/TC-JSON-API#23]
**Operating System**: Ubuntu Server 16.04
**PHP**: PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

I've attached my log file with the error. Any help would be appreciated. :)

[laravel-2016-12-18.txt](https://github.com/ShinDarth/TC-JSON-API/files/659652/laravel-2016-12-18.txt)

**Update**: I noticed the WorldController.php file queries the _world_ database for its version. Upon manually entering the query, MySQL returns "Empty set". Would this cause the Undefined offset error?

**Update #2**: After installing Keira2, it seems to search fine; however, it does display: _ERROR: API not found, please edit your config.js file and set the path of your TrinityCore JSON API istance._ at the top. I have it pointing at the correct file path for the index.php file.

**Fix**: The system queries the _version_ table in the _world_ database for information. In the latest revision of TrinityCore, for a fresh database installation, it seems to not dump this information into the _version_ table, which leads to the "Undefined offset: 0" error in the log file above. The fix is to _manually_ add your version information into the table, and then restart Apache, nginx, or the built-in Web server. (**Note**: This fix was tested on both versions 0.6 and 0.7 of the API.)

**Comment by Helias** [comment]
Thanks for the report, I "fixed" the problem, for the TDB version 355.60+ the welcome page will not show the version.
