### ISSUE TITLE
ERROR: API not found, please edit your config.js file and set the path of your TrinityCore JSON API istance.

### ISSUE THREAD

**Issue by Re3os** [ShinDarth/TC-JSON-API#24]
Error: ERROR: API not found, please edit your config.js file and set the path of your TrinityCore JSON API istance.

Not found his file.
rev: https://github.com/ShinDarth/TC-JSON-API/commit/899e429ae0e99863496b99ef7062988a53f7dc12

Update - > log http://pastebin.com/TZ2gVWaA

**Comment by Helias** [comment]
Is the same of #23

"The fix is to manually add your version information into the table, and then restart Apache, nginx, or the built-in Web server."

**Comment by Helias** [comment]
Thanks for the report, I "fixed" the problem, for the TDB version 355.60+ the welcome page will not show the version.
