### ISSUE TITLE
Login/register route?

### ISSUE THREAD

**Issue by azanoni** [ShinDarth/TC-JSON-API#25]
Its possible made routes for login, logout and register?

**Comment by Helias** [comment]
Login and register is already implemented as you can see here https://github.com/ShinDarth/TC-JSON-API/commit/3efa4e2f43d2a31d945dad3138c3e0a233677baf, but they aren't documented in the wiki.

Anyway we are planning to migrate the TC-JSON-API into this new API written in Symfony https://github.com/azerothcore/apaw

**Comment by azanoni** [comment]
@Helias :(, you dont support anymore trinitycore?

**Comment by Helias** [comment]
Of course we will support it, we will support the platforms trinitycore and azerothcore, azerothcore has the database structure similar to trinitycore

**Comment by azanoni** [comment]
Thanks, only for clarify, TC-JSON-API will be support TrinityCore and "Apaw" will be support Azerothcore rigth?
And you can explain how to use login/register method? because I try to access to: 
http://localhost/TC-JSON-API/public/auth/login or 
http://localhost/TC-JSON-API/public/auth/register

and this is the message: "Sorry, the page you are looking for could not be found."
If this have a forum or another place to ask help please tellme.
Thanks for your support

**Comment by Helias** [comment]
Did you follow this new guide to install the TC-JSON-API?
https://github.com/ShinDarth/TC-JSON-API/blob/master/INSTALL.md

Only the development version supports the authentication so you need to install the latest version from sources. Anyway you can't just go to the path TC-JSON-API/public/auth/login you need to do a POST request with username and password as params, you can use the app [POSTMAN](https://www.getpostman.com/) to test that.

**Comment by azanoni** [comment]
Yes the API-REST works but not this 2 new methods:  I tested using RESTClient in Firefox, try to use the both ways, json request and parameter request like http://localhost/TC-JSON-API/public/auth/login/?username=test&password=test
![imagen](https://cloud.githubusercontent.com/assets/21685626/22607292/03444c68-ea36-11e6-909c-b2c5233ed916.png)

**Comment by avengerweb** [comment]
check routes pls, u missed part of url /api/v1/auth/login

**Comment by azanoni** [comment]
Thanks!, anyone should be update the readme.md, here is the corrects urls:
For login:
http://localhost/TC-JSON-API/public/api/v1/auth/login/?username=test123&password=testtest123
For register:
http://localhost/TC-JSON-API/public/api/v1/auth/register/?username=test123&password=test123&email=huesoamz@gmail.com
