### ISSUE TITLE
Add Access control

### ISSUE THREAD

**Issue by qyh214** [ShinDarth/TC-JSON-API#3]
Access control.For example,connect with other account control center or have own account system that like dev.battle.net ,If it is public, there will be security problems or pose a threat to the server.

**Comment by FrancescoBorzi** [comment]
Agree, I was thinking to add authentication too

**Comment by avengerweb** [comment]
In laravel 5.2 you can do it in both ways, first auth by standart trinitycore way from auth DB and custom auth for API.

**Comment by FrancescoBorzi** [comment]
@avengerweb it would be nice to have it from the auth DB, would you like to work on it?

**Comment by avengerweb** [comment]
That easy, I will make it on weekends.

**Comment by FrancescoBorzi** [comment]
Great, thanks.

**Comment by avengerweb** [comment]
Done in #18
