### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by 0xCiBeR** [ShinDarth/TC-JSON-API#31]
Hey, i'm getting a 404 not found on any route. I can see public/index.php just fine, but i can't access any route. 
![image](https://user-images.githubusercontent.com/9750850/45434545-13915f80-b685-11e8-9e21-d025aea9c8fe.png)
![image](https://user-images.githubusercontent.com/9750850/45434562-1e4bf480-b685-11e8-9936-ddec4b99707c.png)

**Comment by FrancescoBorzi** [comment]
try specifying `index.php` in the URL. For example:

`localhost/api/public/index.php/uptime`.

Be aware that this project was just a rough experiment and it's not supported anymore.
