### ISSUE TITLE
quest_template struct has been changed

### ISSUE THREAD

**Issue by lyrl** [ShinDarth/TC-JSON-API#5]
quest_template struct has been changed
ref: 2015_06_23_00_world_335.sql

**Comment by FrancescoBorzi** [comment]
I know, I did those changes in TrinityCore. However this should already fix the API for the latest TrinityCore:

https://github.com/ShinDarth/TC-JSON-API/commit/e8cf3f86e424c850537ea958f4c8cd9accd0f0c1

so you have yo use latest source revision from source, or wait for the next FULL release.

If you think it's still bugged, even in the latest APIsource revision, feel free to open a new issue.

Thank you for helping!
