### ISSUE TITLE
Error while processing compiled.php

### ISSUE THREAD

**Issue by Niknox** [ShinDarth/TC-JSON-API#8]
I installed your API v0.5. Sadly the index page is not loading.

Error in storage/logs:
`production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 60 seconds exceeded' in [...]/TC-JSON-API/vendor/compiled.php:11934
Stack trace:
#0 {main}`

Could this be a problem on your side? It seems that the script is not terminating.

System info:
Debian Jessie
PHP 5.6 latest; compiled amongst others with the from this project needed support for: mcrypt, sqlite, openssl, mbstring, tokenizer
Apache 2.4 latest

**Comment by Niknox** [comment]
I checked out the line, it's a mcrypt function.
This might be a problem on my side, will investigate this. I'm running libmcrypt 2.5.8.
Edit: Didn't find anything wrong. Mcrypt is correctly enabled in phpinfo().

**Comment by FrancescoBorzi** [comment]
Try https://www.daniweb.com/web-development/php/threads/372491/how-to-fix-fatal-error-maximum-execution-time-of-60-seconds-exceeded-in-php

**Comment by Niknox** [comment]
I'll try with a higher value. But if your script really consumes that much time, that might be due to inefficient coding, no offense.

**Comment by FrancescoBorzi** [comment]
That is just an attempt to understand what is happening, because I have never got such an error and I did a lot of tests. There is no reason to take so much time to load, especially for the index page

**Comment by Niknox** [comment]
Did not bring any change, switched it to 3min.

**Comment by FrancescoBorzi** [comment]
Did you download the latest release or installed from latest sources?

**Comment by Niknox** [comment]
I downloaded the latest release because I didn't want to install Composer and Laravel.

**Comment by FrancescoBorzi** [comment]
Yes that should be ok. Googling your error I found it may be the port, which port are you using?

**Comment by Niknox** [comment]
Mysql port? 3306 standard.
Edit: Communication in trinity irc or somewhere else would be easier if you want :)

**Comment by Niknox** [comment]
Issue clear, caused by: https://bugs.php.net/bug.php?id=69833
